print('Welcome to the Band Name Generator.')
# print(f"Welcome to the Band Name Generator.")
# city = input("What\'s name of the city you grew up in?")
# pet = input("What\'s your pet\'s name?")
# print(f"Your band name could be {city} {pet}")
# print("Your band name could be " + city + " " + pet)
print("Your band name could be " + input("What\'s the name of the city you grew up in?  ") + " " + input("What\'s your pet\'s name?  "))