print('Welcome to the tip calculator.')
total_bill = float(input('What is the total bill? $'))
percentage_tip = float(input('What percentage tip would you like to give? 10, 12 or 15? ') )
no_of_people = int(input('How many people to split the bill? '))
total_percentage_tip = float(1 + (percentage_tip / 100))
amount_to_be_payed = float((total_bill / no_of_people) * total_percentage_tip)
print(round(amount_to_be_payed, 2))